apiVersion: v1alpha1
kind: Role
metadata:
  name: hitokoto-hub-role-template-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Hitokoto Hub"
    rbac.authorization.halo.run/display-name: "一言管理"
    rbac.authorization.halo.run/dependencies: |
      ["hitokoto-hub-role-template-view"]
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:hitokoto-hub:manage"]
rules:
  - apiGroups: [ "hitokotohub.puresky.top" ]
    resources: [ "sentences", "categories", "sentencesubmissions", "aigeneratelogs", "similaritychecklogs" ]
    verbs: [ "create", "delete", "deletecollection", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "console.api.hitokotohub.puresky.top" ]
    resources: [ "sentence/batch", "sentence/import-excel", "sentence-submissions", "sentence-submissions/approve", "sentence-submissions/reject", "ai-generate-logs", "ai-generate-logs/-/trigger", "similarity-check-logs", "similarity-check-logs/-/trigger", "similarity-check-config" ]
    verbs: [ "create", "delete", "get", "list" ]
