apiVersion: v1alpha1
kind: Role
metadata:
  name: hitokoto-hub-role-template-public
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "Hitokoto Hub"
    rbac.authorization.halo.run/display-name: "一言公共接口"
rules:
  - apiGroups: [ "public.api.hitokotohub.puresky.top" ]
    resources: [ "sentence", "category", "sentence-submission", "sentence-submission/config" ]
    verbs: [ "get", "list", "create" ]
