apiVersion: v1alpha1
kind: Role
metadata:
  name: hitokoto-hub-role-template-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Hitokoto Hub"
    rbac.authorization.halo.run/display-name: "一言查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:hitokoto-hub:view"]
rules:
  - apiGroups: [ "console.api.hitokotohub.puresky.top" ]
    resources:
      - "sentence"
      - "sentence/share"
      - "sentence/share/card"
      - "overview"
      - "ai-generate-logs"
      - "sentence-submissions"
      - "similarity-check-logs"
      - "categories"
      - "similarity-check-config"
      - "similarity-check-groups"
    verbs: [ "get", "list" ]
  - apiGroups: [ "hitokotohub.puresky.top" ]
    resources:
      - "categoryviewrecords"
      - "sentences"
      - "sentencesubmissions"
      - "categories"
      - "aigeneratelogs"
      - "similaritychecklogs"
    verbs: [ "get", "list", "watch" ]
