apiVersion: v1alpha1
kind: Role
metadata:
  name: hitokoto-hub-role-template-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Hitokoto Hub"
    rbac.authorization.halo.run/display-name: "一言管理"
    rbac.authorization.halo.run/dependencies: |
      ["hitokoto-hub-role-template-view"]
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:hitokoto-hub:manage"]
rules:
  - apiGroups: [ "console.api.hitokotohub.puresky.top" ]
    resources:
      - "ai-generate-logs/trigger"
      - "sentence/batch"
      - "sentence/import-excel"
      - "similarity-check-groups/delete-nonoptimal"
      - "similarity-check-logs/trigger"
      - "sentence/clear-uncategorized"
    resourceNames: [ "-" ]
    verbs: [ "create", "delete" ]
  - apiGroups: [ "console.api.hitokotohub.puresky.top" ]
    resources:
      - "sentence-submissions"
      - "sentence-submissions/approve"
      - "sentence-submissions/reject"
      - "ai-generate-logs"
    verbs: [ "create", "delete" ]
  - apiGroups: [ "hitokotohub.puresky.top" ]
    resources:
      - "categoryviewrecords"
      - "sentences"
      - "sentencesubmissions"
      - "categories"
      - "aigeneratelogs"
      - "similaritychecklogs"
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
